version: '3'
services:
  learning-wp.local:
    container_name: learning-wp.local
    image: pagevamp/nginx-php7-fpm:7.2
    restart: always
    environment:
      - VIRTUAL_HOST=learning-wp.local
    volumes:
      - ./:/var/www
      - ./docker/sites/default.conf:/etc/nginx/sites-enabled/default
    networks:
      - pagevamp
networks:
  pagevamp:
    external: true
